CHANGELOG.md
src/Dialog/Dialog.tsx
src/Header/Header.tsx
src/IconButton/IconButton.tsx
src/Pagination/CustomTablePaginationActions.tsx
src/Panel/Panel.tsx
src/Panel/PanelTabs.tsx
src/Snackbar/Snackbar.tsx
src/Tabs/Tab.tsx
src/Tabs/Tabs.tsx

Added tooltips to the icons in the pagination, dialog, header, and snackbar components.

Added tooltip for dialog and pagination icons

---

CHANGELOG.md
src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.tsx
src/composite_components/MultipleSelectChip/MultipleSelectChip.stories.tsx
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

Added `tooltipPlacement` prop to the `MultipleSelectChip` & `Autocomplete` component.

DXQ-39501 - change input field helper tooltip position to top

---

CHANGELOG.md
src/TextField/TextField.stories.tsx
src/TextField/TextField.tsx
src/__tests__/unit/TextField/TextField.test.tsx
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

The a11y props from https://mui.com/material-ui/react-text-field/#accessibility were slightly misaligned as there was a duplicate label calculation function.
This PR introduces the id as an optional field to define the id to use for the attributes `for`, `id`, and `aria-describedby`, and corrects the internal usage of the id to relate the fields of the FormControl.
Before:
After:

Textfield a11y - Correct htmlFor and id attribute for TextField input label and input

---

CHANGELOG.md
src/Snackbar/Snackbar.tsx

Added `role="alert"` to the snackbar message text for improved screen reader accessibility.

Added role for screen readers to announce the snackbar message

---

.storybook/main.js
CHANGELOG.md
src/Dialog/Dialog.mdx

- Added developer notes in Dialog component's storybook docs

Update Dialog component Storybook docs

---

CHANGELOG.md
src/Pagination/CustomTablePaginationActions.tsx
src/__tests__/unit/Pagination/Pagination.test.tsx

- Added `aria-label` to the input field for the pagination row label and page label to enhance screen reader accessibility.

Pagination a11y - Add aria-label to Show rows and Page field

---

README.md

Some consumers of the library may not want its styling to affect the outer page, if they are not fully committed to Enchanted yet, so included an example of using `<ScopedCssBaseline>`

Mention ScopedCssBaseline in README.md

---

CHANGELOG.md
src/Pagination/CustomTablePaginationActions.tsx
src/Pagination/Pagination.tsx
src/__tests__/unit/Pagination/Pagination.test.tsx
src/composite_components/ProgressBar/ProgressHeader.tsx

- Fixed screen reader accessibility issue with the pagination `label` in the `Pagination` component.
- Fixed focus handling on the expand/collapse icon button in the `ProgressBar` component to address focus accessibility issues

Fixed a11y issue with pagination label

---

CHANGELOG.md
src/DataGrid/DataGrid.stories.tsx
src/DataGrid/DataGrid.tsx
src/DataGrid/sampleData.tsx
src/DataGridCell/DataGridCell.stories.tsx
src/DataGridCell/DataGridCell.tsx
src/DataGridCell/sampleCellConfig.tsx
src/__tests__/unit/DataGrid/DataGridCell.test.tsx

- Added `subTitle` to the `DataGridCell` component to display additional subtitle text in the row data.
Examples -

Added subTitle to the DataGridCell

---

CHANGELOG.md
src/Button/Button.stories.tsx
src/Button/Button.tsx
src/__tests__/unit/Button/Button.test.tsx

This PR covers the following changes:
- Added a "neutral" option on the size property of the Button component
Design link: https://www.figma.com/design/dnJs5qGUrh1jkQr7y6md7U/branch/gc7YruvOgqnK3naHkgcSNw/HCLED-Components-V2.1?node-id=1338-465763&t=Dq4gTLscP5JNWCZH-0

Add neutral size option to Button component

---

CHANGELOG.md
src/DatePicker/DatePicker.tsx

Date picker icon button shows on focus after selecting a date on mouse navigation.
https://jira.cwp.pnp-hcl.com/browse/DXQ-30425

[WCAG 2.1 2.4.3] Date picker icon shows on focus

---

CHANGELOG.md
src/Button/Button.tsx
src/TextField/TextField.stories.tsx
src/__tests__/unit/UnitSelector/UnitSelector.test.tsx
src/composite_components/ProgressBar/ProgressItems.tsx
src/prerequisite_components/UnitSelector/UnitSelector.tsx
src/prerequisite_components/UnitSelector/index.ts

This PR covers the following changes:
- Created a UnitSelector component under prerequisite_components
- Apply this component to the InputProps endAdornment of TextField
- Create examples in TextField stories
Design link: https://www.figma.com/design/IQYr8v2tFkJDPcx31sJCkH/Presentation-Designer?node-id=8134-13325&t=tkC8mr2zpg984ERt-0

Create Unit Selector component

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx

**Issue:** the screen reader does not narrate the label of the Autocomplete input field
**Fix:** Added `aria-labelledby` to the inputProps of the TextField in the Autocomplete component to properly associate the input with its label for screen readers.

Fix a11y issue - NVDA doesn't read label for Autocomplete

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx

Fixed pagination wrong rendered page number issue by removing textfield input control from `Autocomplete`
- autocomplete when used in pagination component: page 1 should show page 1, not page 0
- autocomplete when used standalone or any other use case: value of textfield should be controlled by renderInput (textfieldArgs.value, not textfieldArgs.inputPropsValue)
Fixed:
https://github.com/user-attachments/assets/e1705ca7-1729-4382-9fb1-d978142a606a
https://github.com/user-attachments/assets/95799242-9874-4667-a7ac-b19df7b3a12f
The Bug:

Fix Pagination issue with Autocomplete

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx

Should allow typing on MultiSelectChip again
See bug video here: https://jira.cwp.pnp-hcl.com/browse/DXQ-43317
Undo this fix: https://github.com/HCL-TECH-SOFTWARE/enchanted-react-components/pull/147

undo inputPropsValue arg totally - makes freesolo typing on MultiSelectChip impossible (based on Autocomplete)

---

CHANGELOG.md
src/Popper/Popper.tsx

- Added tooltip for close button in Popper component
- Fixed extra space below the popper title
Before:
After:

Add tooltip for close button and fix extra space in in Popper component

---

CHANGELOG.md
src/List/ListItemButton.tsx

This PR contains the updated CSS to remove pointer and focus on Hover from a cancelled item in progressbar items list.
Jira: https://jira.cwp.pnp-hcl.com/browse/DXQ-43488
[Enchanted UI PR](https://github.com/nidhinrajr/enchanted-ui/pull/12)

Progress bar css  fix for cancelled items

---

CHANGELOG.md
src/List/ListItemButton.tsx
src/composite_components/ProgressBar/ProgressItems.tsx

Fixed CSS override issue. disable hover CSS was working fine in storybook but in DAM due to override issue the disabled hover css was not reflecting correctly. HEnce fixed the issue. Below are the verification details.
StoryBook : 
npm run build, replaced dist folder from hcl-software/enchanted-react-components into Media library
In DAM, did Make install then Import progressbar from enchanted-react component (only this change required).
Verified in DAM, CSS is reflecting. 
[enchanted-ui PR (**merged**)](https://github.com/nidhinrajr/enchanted-ui/pull/13)
Verfied the changes in DAM locally and in native-kube as well post enchanted-ui PR merged. 
[Media library PR with native kube details and verification](https://git.cwp.pnp-hcl.com/websphere-portal-incubator/media-library/pull/3753)

Ensure cancelled items ignore hover and click events - Progress bar

---

CHANGELOG.md
src/composite_components/ProgressBar/ProgressItems.tsx

This PR resolved the issue where tooltips on progress bars would float outside their parent container when hovering over and scrolling through uploaded items.

fix: tooltip in progress bar

---

CHANGELOG.md
src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.tsx
src/DatePicker/DatePicker.stories.tsx
src/DatePicker/DatePicker.tsx
src/Select/Select.tsx
src/Select/SelectMultiple.stories.tsx
src/TextField/TextField.stories.tsx
src/TextField/TextField.tsx
src/composite_components/MultipleSelectChip/MultipleSelectChip.stories.tsx
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

Jira ticket: https://hclsw-jirads.atlassian.net/browse/DXQ-41961
Changes
- Added a tabIndex to the MuiHelperIcon so it can be read by screen readers.
- Added an enableHoverEffect to provide a gray shade on the help icon when hovered.

DXQ-41961-enable-to-read-the-information-icon-on-the-Content-Element

---

CHANGELOG.md
src/Autocomplete/Autocomplete.stories.tsx
src/Autocomplete/Autocomplete.tsx

Jira Ticket: https://hclsw-jirads.atlassian.net/browse/DXQ-43848
Tooltip
1. Look for long words Ex. The Lord of the Rings: The Return of the King
2. Then Select that word
3.  Ctrl + A, Then type Sha
4. Then Click tab
1. Look for long words Ex. The Lord of the Rings: The Return of the King
2. Ctrl + A, then type any word
3. Then click tab
Expected: The last type that we did is now a tooltip
Actual: it should be the one that is set on the field
Jira Ticket: https://hclsw-jirads.atlassian.net/browse/DXQ-45590
Truncate

DXQ-43848-Text-(Font)---Tooltip-and-ellipse-issue
