CHANGELOG.md
src/Icon/Icon.stories.tsx

Noticed list--edit is not being shown off in IconPreview.stories just yet, added it

task: add list--edit icon to IconPreview stories

---

CHANGELOG.md
src/Preview/Preview.tsx

Added props for error handling in preview component

Error handler in Preview component

---

CHANGELOG.md
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

Added handleClick to the ActionProps in the InputLabelAndAction component

Click handler in InputLabelAndAction component

---

CHANGELOG.md
src/Link/Link.stories.tsx
src/Link/Link.tsx
src/Preview/Preview.tsx
src/__tests__/unit/Link/Link.test.tsx

This PR covers the following changes:
1.) Fix css of link component
2.) Add visual test for consistency with other components

Implement link component with stories

---

CHANGELOG.md
src/Panel/Panel.stories.tsx
src/Panel/Panel.tsx
src/Panel/PanelTabContent.tsx
src/Panel/PanelTabs.tsx
src/Tabs/Tabs.tsx

Added a toggle button to the panel component.
Adjusted the text alignment of the Tab component.

Toggle button for panel component & css fixes

---

CHANGELOG.md
src/Accordion/Accordion.stories.tsx
src/Accordion/AccordionSummary.tsx
src/composite_components/Tile/Tile.stories.tsx
src/composite_components/Tile/Tile.tsx

- Added hover actions for the Accordion component
- Added sync icon for the Tile component

Added hover action for accordion component

---

CHANGELOG.md
src/__tests__/unit/composite-components/ProgressBar/ProgressBar.test.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressHeader.test.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressItem.test.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressSubHeader.test.tsx
src/composite_components/ProgressBar/ProgressBar.stories.tsx
src/composite_components/ProgressBar/ProgressBar.tsx
src/composite_components/ProgressBar/ProgressHeader.tsx
src/composite_components/ProgressBar/ProgressItems.tsx
src/composite_components/ProgressBar/ProgressSubHeader.tsx
src/composite_components/ProgressBar/index.ts
src/index.ts

ProgressBar component

---

CHANGELOG.md
src/ToggleButton/ToggleButton.stories.tsx
src/ToggleButton/ToggleButton.tsx
src/ToggleButtonGroup/ToggleButtonGroup.stories.tsx
src/ToggleButtonGroup/ToggleButtonGroup.tsx
src/ToggleButtonGroup/index.ts
src/__tests__/unit/ToggleButtonGroup/ToggleButtonGroup.test.tsx
src/index.ts
src/theme/index.ts

Add ToggleButtonGroup component

---

src/IconButton/IconButton.stories.tsx
src/IconButton/IconButton.tsx

Fix issue in onClick and onFocus events of IconButton

Fix issue in onClick and onFocus events of IconButton

---

CHANGELOG.md
src/List/ListItemButton.tsx
src/Panel/PanelTabs.tsx
src/Tabs/Tabs.tsx
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

Added disabled and tooltip to the ActionProps in the InputLabelAndAction component.
Fixed the issue with clicking on secondary actions in the ListItemButton component and tab clicks in the Panel component.

Added Tooltip and disabled props for InputLabelAndAction

---

CHANGELOG.md
src/Accordion/AccordionSummary.tsx
src/IconButton/IconButton.tsx
src/List/ListItemButton.tsx
src/PreviewAccordion/PreviewAccordion.stories.tsx
src/PreviewAccordion/PreviewAccordion.tsx
src/PreviewAccordion/PreviewAccordionDetails.tsx
src/PreviewAccordion/PreviewAccordionSummary.tsx
src/PreviewAccordion/index.ts
src/ProgressIndicator/CircularProgress/CircularProgress.tsx
src/Tabs/Tabs.tsx
src/__tests__/unit/PreviewAccordion/PreviewAccordion.test.tsx

Added `PreviewAccordion` component
Added `withbackdrop` props to the circular progress component
Corrected iconbutton space in list & accordion component

Added PreviewAccordion Component

---

CHANGELOG.md
src/Avatar/Avatar.tsx
src/Breadcrumbs/Breadcrumbs.tsx
src/IconButton/IconButton.tsx
src/Panel/Panel.stories.tsx
src/Panel/PanelTabContent.tsx
src/ProgressIndicator/CircularProgress/CircularProgress.tsx
src/composite_components/Tile/Tile.tsx

Updated breadcrumb icons to reflect directionality (RTL/LTR)
Resolved spacing issues for icon buttons in the panel component
Fix for console warnings in CircularProgress component

corrected icon for RTL & panel icon spacing

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx
src/DataGrid/DataGrid.tsx
src/Pagination/Pagination.tsx
src/Panel/Panel.tsx
src/Panel/PanelTabs.tsx
src/Snackbar/Snackbar.tsx
src/composite_components/Tile/TileActionBar.tsx
src/composite_components/Tile/TileData.tsx

Corrected panel tooltip position and icon button alignment in Snackbar
Adjusted checkbox alignment in DataGrid component

Corrected panel tooltip position and icon button alignment in snackbar

---

CHANGELOG.md
src/Snackbar/Snackbar.stories.tsx
src/Snackbar/SnackbarContainer.tsx

- Added a configurable optional property for `Snackbar` position

Configurable SnackBar Position

---

CHANGELOG.md
package.json
src/List/ListItemText.tsx

Fix tooltip issue of Autocomplete component

---

CHANGELOG.md
src/Header/Header.tsx
src/__tests__/unit/Header/Header.test.tsx

This PR covers the following changes:
1.) Added a favoritesToggleComponent props to the Header component

Add favoritesToggleComponent props to Header component

---

CHANGELOG.md
src/Select/Select.tsx

- Fixed screen reader accessibility issue with `Select` component

Screen reader accessibility is fixed on select component

---

CHANGELOG.md
src/Header/Header.tsx
src/Select/Select.tsx

- Fixed helper text on `select` component.

Fixed helper text on select component 

---

CHANGELOG.md
src/List/List.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressItem.test.tsx
src/composite_components/ProgressBar/ProgressItems.tsx

- Fixed focus issue for different status icon buttons in the ProgressBar component

A11y progressBar item status icon button

---

CHANGELOG.md
src/Button/Button.tsx

Fixed button height to align with the design

Corrected button height as per design

---

CHANGELOG.md
src/Pagination/Pagination.tsx

- Text-spacing accessibility issue is fixed on pagination Component.

Textspacing issue is fixed on pagination Component

---

CHANGELOG.md
src/Button/Button.stories.tsx
src/Button/Button.tsx
src/Preview/Preview.tsx
src/__tests__/unit/Button/Button.test.tsx

Added inversecolor property in button

Added inversecolor property in button

---

CHANGELOG.md
src/DataGridCell/DataGridCell.tsx
src/Preview/Preview.tsx

Fixed screen reader accessibility issue with the zoom in & zoom out button in the Preview component.

Announcing status fix  in preview

---

.jest-reporter-log-validator-config.json
CHANGELOG.md
src/ActionButton/ActionButton.stories.tsx
src/ActionButton/ActionButton.tsx
src/ActionButton/index.ts
src/__tests__/unit/ActionButton/ActionButton.test.tsx
src/__tests__/unit/Autocomplete/Autocomplete.test.tsx
src/__tests__/unit/Select/Select.test.tsx
src/__tests__/unit/TextField/TextField.test.tsx
src/index.ts
src/prerequisite_components/InputLabelAndAction/InputLabelAndAction.tsx

- Implemented `ActionButton` component
The `href` property is associated with `actionProps` in the `InputLabelAndAction` component because the `Link` component is used for actions.
To prevent application breakage when using the `ActionButton` component, we have implemented logic to handle `href` behavior within the `ActionButton` itself. If the `href` property is provided, the component navigates to the specified URL. Otherwise, it triggers the `handleClick` function (if defined), allowing for custom actions when clicked. This ensures flexibility in the button's behavior based on the provided properties.

Action Button component

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx

Fixed flickering issue in the autocomplete component when going to the next or previous page using pagination

Fix pagination flickering

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx
src/TextField/TextField.tsx

DXQ-36099-Autocomplete-component-help-text-position-is-wrong-when-text-direction-is-RTL

---

.jest-reporter-log-validator-config.json
CHANGELOG.md
src/DataGrid/DataGrid.stories.tsx
src/DataGrid/DataGrid.tsx
src/DataGrid/sampleData.tsx
src/DataGridCell/DataGridCell.tsx
src/utils/eventUtils.ts

- accessibility issue on disabled row is fixed

accessibility issue on disabled row in DataGrid

---

CHANGELOG.md
src/DatePicker/DatePicker.tsx

Changes added for handling the focus on the date pickers dialog

Changes added for handling the focus on the date pickers dialog

---

CHANGELOG.md

Added the comment on the unreleased

Added the comment on the unreleased

---

CHANGELOG.md
src/composite_components/ProgressBar/ProgressItems.tsx

- Fixed the issue where the 'Learn more' button shifted when hovering over the list of progress items in the `ProgressBar` component.

"Learn more" button moves while hovering

---

CHANGELOG.md
src/List/ListItemButton.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressItem.test.tsx
src/__tests__/unit/composite-components/ProgressBar/ProgressSubHeader.test.tsx
src/composite_components/ProgressBar/ProgressBar.stories.tsx
src/composite_components/ProgressBar/ProgressBar.tsx
src/composite_components/ProgressBar/ProgressHeader.tsx
src/composite_components/ProgressBar/ProgressItems.tsx
src/composite_components/ProgressBar/ProgressSubHeader.tsx

Jira: https://jira.cwp.pnp-hcl.com/browse/DXQ-43488
Changes: 
1- Removed cancel all button from progressbar subheader
2- Removed focus on hover from cancelled item in progress bar item list.
3- fixed cancel all disabled state css.
https://github.com/user-attachments/assets/5ebb577f-d03a-4780-9a84-176afc3d0502

Progress bar cancel all feature enhancement

---

CHANGELOG.md
src/TextField/TextField.tsx

Reference Issue: https://github.com/HCL-TECH-SOFTWARE/enchanted-react-components/issues/118

Changed Placeholder color for TextField with multiline

---

CHANGELOG.md
src/Tabs/Tab.tsx

https://github.com/HCL-TECH-SOFTWARE/enchanted-react-components/issues/124--->fix

Fix tolltip issue on tab hover

---

CHANGELOG.md
src/Accordion/Accordion.stories.tsx
src/Accordion/Accordion.tsx

Fix accordion for square prop

---

.jest-reporter-log-validator-config.json
src/Breadcrumbs/BadgeFilterButton.tsx
src/Breadcrumbs/Breadcrumbs.stories.tsx
src/Header/sampleHeaderConfig.tsx
src/Link/Link.tsx
src/__tests__/unit/Breadcrumbs/Breadcrumbs.test.tsx
src/__tests__/unit/Header/Header.test.tsx

As part of this Story we are going to cover the Badge in the Header section of StoryBook and SortOptions in the header and add CollectionSort to the Breadcrumb section.

DXQ-44233-sort-filter-badge

---

CHANGELOG.md
src/Panel/Panel.stories.tsx
src/Panel/Panel.tsx
src/Panel/PanelTabs.tsx

JIRA: https://hclsw-jirads.atlassian.net/browse/DXQ-42077
This PR covers the following change:
- Added the togglePanelLabel props in Panel and PanelTabs components

Add new props in Panel and PanelTabs

---

CHANGELOG.md
src/Autocomplete/Autocomplete.tsx

Jira Ticket: https://hclsw-jirads.atlassian.net/browse/DXQ-45590
Issue: Regarding on the ellipses, there is available space that is not being utilized

DXQ-45590-Bidi-Normal-words-is-truncated-even-there-is-available-space-in-Autocomplete
